# Generated by Django 6.0.4 on 2026-04-16 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('conc_rate', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('default_miles', models.IntegerField(default=0)),
                ('zone', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BudgetTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('scope', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('has_base_cost', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['scope', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTradeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CraftsmanPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('paint_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stain_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('miles_tier', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('stories', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('ext_wall_sf', models.IntegerField(default=0)),
                ('dbl_doors', models.IntegerField(default=0)),
                ('sgl_doors', models.IntegerField(default=0)),
                ('dbl_windows', models.IntegerField(default=0)),
                ('sgl_windows', models.IntegerField(default=0)),
                ('p10_material', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cabinetry_lf_display', models.CharField(blank=True, max_length=20)),
                ('cabinetry_lf_num', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('island_depth', models.IntegerField(default=3)),
                ('island_width', models.IntegerField(default=8)),
                ('island_label', models.CharField(blank=True, max_length=20)),
                ('pdf_pages', models.IntegerField(default=2)),
                ('is_custom', models.BooleanField(default=False)),
                ('int_contract', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cabinet_top_line', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf_filename', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InteriorRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IslandAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_addr', models.CharField(blank=True, max_length=300)),
                ('sales_rep', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('job_mode', models.CharField(choices=[('shell', 'Shell Only'), ('turnkey', 'Turnkey Interior')], default='shell', max_length=10)),
                ('miles_over_100', models.BooleanField(default=False)),
                ('p10_material', models.DecimalField(decimal_places=2, default=0, help_text='Auto-filled from model P10 but editable', max_digits=12)),
                ('foundation_type', models.CharField(default='concrete', max_length=10)),
                ('basement_framing', models.BooleanField(default=False)),
                ('crawl_sf', models.IntegerField(default=0)),
                ('stories', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('wall_type', models.CharField(default='Metal', max_length=30)),
                ('wall_tuff_sf', models.IntegerField(default=0)),
                ('wainscot_enabled', models.BooleanField(default=False)),
                ('wall_rock_sf', models.IntegerField(default=0)),
                ('wall_stone_sf', models.IntegerField(default=0)),
                ('stone_upgrade', models.BooleanField(default=False)),
                ('sheathing', models.BooleanField(default=False)),
                ('gauge_26', models.BooleanField(default=False)),
                ('awning_qty', models.IntegerField(default=0)),
                ('cupola_qty', models.IntegerField(default=0)),
                ('chimney_qty', models.IntegerField(default=0)),
                ('punch_amount', models.DecimalField(decimal_places=2, default=2500, max_digits=10)),
                ('windows_above_12', models.BooleanField(default=False)),
                ('sgl_windows', models.IntegerField(default=0)),
                ('dbl_windows', models.IntegerField(default=0)),
                ('s2s_windows', models.IntegerField(default=0)),
                ('s2d_windows', models.IntegerField(default=0)),
                ('sgl_doors', models.IntegerField(default=0)),
                ('dbl_doors', models.IntegerField(default=0)),
                ('detached_shop', models.BooleanField(default=False)),
                ('deck_shown', models.BooleanField(default=False)),
                ('conc_sqft', models.IntegerField(default=0)),
                ('conc_type', models.CharField(blank=True, max_length=20)),
                ('conc_zone', models.IntegerField(default=1)),
                ('conc_line_pump', models.BooleanField(default=False)),
                ('conc_boom_pump', models.BooleanField(default=False)),
                ('conc_wire', models.BooleanField(default=False)),
                ('conc_rebar', models.BooleanField(default=False)),
                ('conc_foam_lf', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=3)),
                ('full_baths', models.IntegerField(default=2)),
                ('half_baths', models.IntegerField(default=0)),
                ('plumbing_fixtures', models.IntegerField(default=8)),
                ('closet_qty', models.IntegerField(default=3)),
                ('interior_doors', models.IntegerField(default=15)),
                ('laundry_sink', models.BooleanField(default=False)),
                ('modified_cab_lf', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('modified_island_depth', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('modified_island_width', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('island_addon', models.CharField(blank=True, max_length=30)),
                ('appliance_config', models.CharField(default='standard_range_mw', max_length=40)),
                ('counter_sf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('flooring_sf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('trim_lf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('drywall_sf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dw_sheets', models.IntegerField(default=0)),
                ('paint_sf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hvac_tons', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('insulation_sf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cabinet_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('countertop_notes', models.TextField(blank=True)),
                ('gas_type', models.CharField(blank=True, max_length=10)),
                ('int_true_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjusted_int_contract', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('int_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('int_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ext_labor_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ext_labor_profit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('margin_div', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upgrade_adder', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_budgeted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_price_allocation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='JobCabinetCustomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCabinetUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('lf_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobConcreteFinishLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rate_per_sf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sqft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobContractorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=30)),
                ('override_qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobCountertopArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('rate_per_sf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sqft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobCraftsmanSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('finish', models.CharField(blank=True, choices=[('', 'None'), ('paint', 'Craftsman Paint'), ('stain', 'Craftsman Stain')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Full credit amount (NOT × 0.80 — entire expense eliminated)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobCustomCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('exterior', 'Exterior'), ('concrete', 'Concrete')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='SF', max_length=5)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobCustomCraftsmanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(max_length=10)),
                ('lf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='JobCustomUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('flat', 'Flat Rate'), ('per_unit', 'Per SF/LF')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='SF', max_length=5)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobRoofRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=40)),
                ('roof_type', models.CharField(choices=[('metal', 'Metal'), ('ss', 'Standing Seam'), ('shingles', 'Shingles')], default='metal', max_length=10)),
                ('steep', models.BooleanField(default=False)),
                ('sqft', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='JobSelectionCustomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill', models.CharField(choices=[('docusign', 'Docusign'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('trim', 'Interior Trim')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobSlabRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=40)),
                ('sqft', models.IntegerField(default=0)),
                ('tg_ceiling', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='JobUpgradeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('sf_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lf_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoofAreaPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=40)),
                ('sqft', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SlabAreaPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=40)),
                ('sqft', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('step', models.CharField(choices=[('cabinets', 'Step 6 - Cabinets'), ('countertops', 'Step 6 - Countertops'), ('docusign', 'Step 7 - Docusign Upgrades'), ('electrical', 'Step 7 - Electrical'), ('plumbing', 'Step 7 - Plumbing'), ('trim', 'Step 7 - Interior Trim & Flooring'), ('custom', 'Step 7 - Custom')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Upgrade Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('input_type', models.CharField(choices=[('toggle', 'Checkbox (flat cost)'), ('qty', 'Quantity stepper'), ('sf', 'Square footage input'), ('lf', 'Linear footage input'), ('radio', 'Radio buttons (informational)')], max_length=10)),
                ('unit', models.CharField(default='each', max_length=10)),
                ('true_cost_multiplier', models.DecimalField(decimal_places=2, default=0.8, help_text='Usually 0.80 (20% margin). Set to 1.0 for pass-through.', max_digits=4)),
                ('has_base_addon', models.BooleanField(default=False)),
                ('base_addon_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adds_fixture_points', models.DecimalField(decimal_places=1, default=0, help_text='Plumbing fixture points added (e.g. 1.0 for sink stub, 0.5 for ice line)', max_digits=4)),
                ('is_split_budget', models.BooleanField(default=False, help_text='True for tankless WH: 50% to materials, +1 fixture point')),
                ('has_note_box', models.BooleanField(default=False, help_text='Shows text input when qty > 0 (cabinet inserts)')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UpgradeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='changeorder',
            name='idx_change_orders_project',
        ),
        migrations.RemoveIndex(
            model_name='changeorder',
            name='idx_change_orders_status',
        ),
        migrations.RemoveConstraint(
            model_name='changeorder',
            name='change_orders_project_number_uniq',
        ),
        migrations.RemoveIndex(
            model_name='changeorderitem',
            name='idx_co_items_co',
        ),
        migrations.RemoveIndex(
            model_name='contracteditlog',
            name='idx_edit_log_project',
        ),
        migrations.RemoveIndex(
            model_name='contracteditlog',
            name='idx_edit_log_time',
        ),
        migrations.RemoveIndex(
            model_name='modeldefaultmetric',
            name='idx_model_metrics_model',
        ),
        migrations.RemoveConstraint(
            model_name='modeldefaultmetric',
            name='model_default_metrics_model_metric_uniq',
        ),
        migrations.RemoveIndex(
            model_name='modelregionalpricing',
            name='idx_model_pricing_model',
        ),
        migrations.RemoveIndex(
            model_name='modelregionalpricing',
            name='idx_model_pricing_region',
        ),
        migrations.RemoveConstraint(
            model_name='modelregionalpricing',
            name='model_regional_pricing_model_region_uniq',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notifications_recipient',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notifications_time',
        ),
        migrations.RemoveIndex(
            model_name='opsuser',
            name='idx_users_role',
        ),
        migrations.RemoveIndex(
            model_name='opsuser',
            name='idx_users_region',
        ),
        migrations.RemoveIndex(
            model_name='p10order',
            name='idx_p10_project',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_status',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_region',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_sales',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_pm',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_projects_model',
        ),
        migrations.RemoveField(
            model_name='projectexteriorpricing',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectconcrete',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectinteriorcontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcabinetcontract',
            name='project',
        ),
        migrations.RemoveIndex(
            model_name='projectbudgetactual',
            name='idx_actuals_project',
        ),
        migrations.RemoveIndex(
            model_name='projectbudgetactual',
            name='idx_actuals_budget_line',
        ),
        migrations.RemoveIndex(
            model_name='projectbudgetline',
            name='idx_budget_lines_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectbudgetline',
            name='project_budget_lines_project_trade_uniq',
        ),
        migrations.RemoveIndex(
            model_name='projectcabinetupgrade',
            name='idx_cab_upgrades_project',
        ),
        migrations.RemoveIndex(
            model_name='projectconcreteline',
            name='idx_concrete_lines_project',
        ),
        migrations.RemoveIndex(
            model_name='projectcontract',
            name='idx_contracts_project',
        ),
        migrations.RemoveIndex(
            model_name='projectcontractorbudget',
            name='idx_contractor_budget_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectcontractorbudget',
            name='project_contractor_budget_project_key_uniq',
        ),
        migrations.RemoveIndex(
            model_name='projectcountertopline',
            name='idx_countertop_project',
        ),
        migrations.RemoveIndex(
            model_name='projectdraw',
            name='idx_draws_project',
        ),
        migrations.RemoveIndex(
            model_name='projectdraw',
            name='idx_draws_status',
        ),
        migrations.RemoveConstraint(
            model_name='projectdraw',
            name='project_draws_project_number_detached_uniq',
        ),
        migrations.RemoveIndex(
            model_name='projectexteriorupgrade',
            name='idx_ext_upgrades_project',
        ),
        migrations.RemoveIndex(
            model_name='projectinteriorupgrade',
            name='idx_int_upgrades_project',
        ),
        migrations.RemoveIndex(
            model_name='projectmetric',
            name='idx_proj_metrics_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectmetric',
            name='project_metrics_project_metric_uniq',
        ),
        migrations.RemoveIndex(
            model_name='projectmetricaudit',
            name='idx_metric_audit_project',
        ),
        migrations.RemoveIndex(
            model_name='ratecarditem',
            name='idx_rate_items_version',
        ),
        migrations.RemoveConstraint(
            model_name='ratecarditem',
            name='rate_card_items_version_key_uniq',
        ),
        migrations.RemoveIndex(
            model_name='ratecardversion',
            name='idx_rate_versions_region',
        ),
        migrations.RemoveIndex(
            model_name='ratecardversion',
            name='idx_rate_versions_current',
        ),
        migrations.RemoveConstraint(
            model_name='ratecardversion',
            name='rate_card_versions_region_label_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='ratecardversion',
            name='rate_card_versions_one_current_per_region',
        ),
        migrations.AddField(
            model_name='budgettraderate',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_mappings', to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='craftsmanpreset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftsman_presets', to='stmc_ops.floorplanmodel'),
        ),
        migrations.AddField(
            model_name='budgettraderate',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.interiorratecard'),
        ),
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stmc_ops.branch'),
        ),
        migrations.AddField(
            model_name='job',
            name='floor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stmc_ops.floorplanmodel'),
        ),
        migrations.AddField(
            model_name='jobbudgetline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobbudgetline',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='jobcabinetcustomline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_custom_lines', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcabinetupgrade',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_upgrades', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobconcretefinishline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_finish_lines', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcontractoroverride',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_overrides', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcountertoparea',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countertop_areas', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcraftsmanselection',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftsman_selections', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcredit',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcredit',
            name='trade',
            field=models.ForeignKey(help_text='Which budget trade gets reduced', on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='jobcustomcharge',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_charges', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcustomcraftsmanrow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_craftsman_rows', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcustomupgrade',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_upgrades', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobcustomupgrade',
            name='trade',
            field=models.ForeignKey(help_text='Which budget trade this routes to', on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='jobroofrow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_rows', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobselectioncustomline',
            name='budget_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='jobselectioncustomline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_custom_lines', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobslabrow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slab_rows', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='jobupgradeselection',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_selections', to='stmc_ops.job'),
        ),
        migrations.AddField(
            model_name='planmetric',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_metrics', to='stmc_ops.floorplanmodel'),
        ),
        migrations.AddField(
            model_name='roofareapreset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_presets', to='stmc_ops.floorplanmodel'),
        ),
        migrations.AddField(
            model_name='slabareapreset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slab_presets', to='stmc_ops.floorplanmodel'),
        ),
        migrations.AddField(
            model_name='upgradeitem',
            name='budget_trade',
            field=models.ForeignKey(blank=True, help_text="Which trade this upgrade's true cost routes to", null=True, on_delete=django.db.models.deletion.SET_NULL, to='stmc_ops.budgettrade'),
        ),
        migrations.AddField(
            model_name='jobupgradeselection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.upgradeitem'),
        ),
        migrations.AddField(
            model_name='jobcabinetupgrade',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stmc_ops.upgradeitem'),
        ),
        migrations.AddField(
            model_name='upgradesection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='stmc_ops.upgradecategory'),
        ),
        migrations.AddField(
            model_name='upgradeitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stmc_ops.upgradesection'),
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='changeorderitem',
            name='change_order',
        ),
        migrations.RemoveField(
            model_name='contracteditlog',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='contracteditlog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='modeldefaultmetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='modeldefaultmetric',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelregionalpricing',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelregionalpricing',
            name='region',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='opsuser',
            name='region',
        ),
        migrations.RemoveField(
            model_name='p10order',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='p10order',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rate_card_version',
        ),
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sales_rep',
        ),
        migrations.DeleteModel(
            name='ProjectExteriorPricing',
        ),
        migrations.DeleteModel(
            name='ProjectConcrete',
        ),
        migrations.DeleteModel(
            name='ProjectInteriorContract',
        ),
        migrations.DeleteModel(
            name='ProjectCabinetContract',
        ),
        migrations.RemoveField(
            model_name='projectbudgetactual',
            name='budget_line',
        ),
        migrations.RemoveField(
            model_name='projectbudgetactual',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='projectbudgetactual',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectbudgetline',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcabinetupgrade',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='projectcabinetupgrade',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectconcreteline',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcontractorbudget',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcountertopline',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='projectcountertopline',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectdraw',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='projectdraw',
            name='phase_completed_by',
        ),
        migrations.RemoveField(
            model_name='projectdraw',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectexteriorupgrade',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='projectexteriorupgrade',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectinteriorupgrade',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='projectinteriorupgrade',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='overridden_by',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmetricaudit',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='projectmetricaudit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ratecarditem',
            name='version',
        ),
        migrations.RemoveField(
            model_name='ratecardversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ratecardversion',
            name='region',
        ),
        migrations.AlterUniqueTogether(
            name='craftsmanpreset',
            unique_together={('model', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='budgettraderate',
            unique_together={('trade', 'rate_card')},
        ),
        migrations.AlterUniqueTogether(
            name='jobbudgetline',
            unique_together={('job', 'trade')},
        ),
        migrations.AlterUniqueTogether(
            name='jobcontractoroverride',
            unique_together={('job', 'item_key')},
        ),
        migrations.AlterUniqueTogether(
            name='jobcraftsmanselection',
            unique_together={('job', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='planmetric',
            unique_together={('model', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='jobupgradeselection',
            unique_together={('job', 'item')},
        ),
        migrations.DeleteModel(
            name='ChangeOrder',
        ),
        migrations.DeleteModel(
            name='ChangeOrderItem',
        ),
        migrations.DeleteModel(
            name='ContractEditLog',
        ),
        migrations.DeleteModel(
            name='ModelDefaultMetric',
        ),
        migrations.DeleteModel(
            name='ModelRegionalPricing',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='P10Order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ModelCatalog',
        ),
        migrations.DeleteModel(
            name='ProjectBudgetActual',
        ),
        migrations.DeleteModel(
            name='ProjectBudgetLine',
        ),
        migrations.DeleteModel(
            name='ProjectCabinetUpgrade',
        ),
        migrations.DeleteModel(
            name='ProjectConcreteLine',
        ),
        migrations.DeleteModel(
            name='ProjectContractorBudget',
        ),
        migrations.DeleteModel(
            name='ProjectCountertopLine',
        ),
        migrations.DeleteModel(
            name='ProjectContract',
        ),
        migrations.DeleteModel(
            name='ProjectDraw',
        ),
        migrations.DeleteModel(
            name='ProjectExteriorUpgrade',
        ),
        migrations.DeleteModel(
            name='ProjectInteriorUpgrade',
        ),
        migrations.DeleteModel(
            name='MetricDefinition',
        ),
        migrations.DeleteModel(
            name='ProjectMetric',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMetricAudit',
        ),
        migrations.DeleteModel(
            name='RateCardItem',
        ),
        migrations.DeleteModel(
            name='OpsUser',
        ),
        migrations.DeleteModel(
            name='RateCardVersion',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
