# Generated by Django 6.0.4 on 2026-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales'), ('pm', 'Project Manager'), ('exec', 'Executive / Owner'), ('admin', 'System Administrator')], max_length=10),
        ),
    ]
