# Generated by Django 6.0.4 on 2026-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sales_closed_at',
            field=models.DateTimeField(blank=True, help_text='Set when sales rep clicks DocuSign or Interior Contracts handoff. Null = In Progress; set = Closed on the sales side.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='wizard_state',
            field=models.JSONField(blank=True, default=dict, help_text='Raw BuildWizard STATE payload, used to rehydrate the wizard on Edit.'),
        ),
    ]
