# Generated by Django 6.0.4 on 2026-04-18 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0002_applianceconfig_branch_budgettrade_budgettraderate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('initials', models.CharField(max_length=4)),
                ('role', models.CharField(choices=[('sales', 'Sales'), ('pm', 'Project Manager'), ('exec', 'Executive / Owner')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='budget_spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='current_draw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='current_phase',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('framing', 'Framing'), ('interior', 'Interior'), ('punch', 'Punch'), ('final', 'Final'), ('closed', 'Closed')], default='estimate', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='draw_stage',
            field=models.CharField(choices=[('draw1', '1st - Deposit'), ('draw2', '2nd - Slab'), ('draw3', '3rd - Framing'), ('draw4', '4th - Dry-In'), ('draw5', '5th - Finishes'), ('draw6', '6th - Final')], default='draw1', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='draw_status',
            field=models.CharField(choices=[('current', 'Current'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('hold', 'Hold'), ('closed', 'Closed')], default='current', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
