# Generated by Django 6.0.4 on 2026-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0002_job_sales_closed_at_job_wizard_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='is_lead',
            field=models.BooleanField(default=False, help_text='True = sales lead (early contact), False = committed contract. Cleared automatically when the wizard is saved.'),
        ),
        migrations.AddField(
            model_name='job',
            name='lead_next_followup',
            field=models.DateField(blank=True, help_text='Optional date the rep plans to next contact the customer.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lead_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral'), ('web', 'Web / Inbound'), ('walk_in', 'Walk-in'), ('trade_show', 'Trade Show'), ('repeat', 'Repeat Customer'), ('other', 'Other')], max_length=20),
        ),
    ]
