# Generated by Django 6.0.4 on 2026-04-23 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0003_job_customer_email_job_customer_phone_job_is_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=64)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('access_token_expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refresh_token_expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by_email', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'QuickBooks Connection',
            },
        ),
        migrations.CreateModel(
            name='QbCustomerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_customer_id', models.CharField(max_length=32)),
                ('realm_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qb_customer_map', to='stmc_ops.job')),
            ],
        ),
        migrations.CreateModel(
            name='QbInvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qb_invoice_id', models.CharField(blank=True, default='', max_length=32)),
                ('qb_invoice_doc_number', models.CharField(blank=True, default='', max_length=32)),
                ('qb_invoice_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('sent', 'Sent to QuickBooks'), ('failed_fallback', 'Local fallback (QB unavailable)')], default='sent', max_length=24)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_events', to='stmc_ops.jobdraw')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_events', to='stmc_ops.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
