# Generated by Django 6.0.4 on 2026-04-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0003_appuser_job_budget_spent_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.IntegerField()),
                ('label', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('p', 'Paid'), ('c', 'Current'), ('x', 'Pending')], default='x', max_length=2)),
                ('paid_date', models.CharField(blank=True, max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_draws', to='stmc_ops.job')),
            ],
            options={
                'ordering': ['draw_number'],
                'unique_together': {('job', 'draw_number')},
            },
        ),
        migrations.CreateModel(
            name='JobTradeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=40)),
                ('budgeted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_trade_budgets', to='stmc_ops.job')),
            ],
            options={
                'ordering': ['sort_order', 'trade_name'],
                'unique_together': {('job', 'trade_name')},
            },
        ),
    ]
