# Generated by Django 6.0.4 on 2026-04-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0004_jobdraw_jobtradebudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='current_phase',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('framing', 'Framing'), ('roughin', 'Rough-In'), ('interior', 'Interior'), ('punch', 'Punch'), ('final', 'Final'), ('closed', 'Closed')], default='estimate', max_length=12),
        ),
    ]
