# Generated by Django 6.0.4 on 2026-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0004_qbconnection_qbcustomermap_qbinvoiceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbSyncSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('stale', 'Stale (last pull failed)'), ('offline', 'QB not connected')], default='offline', max_length=16)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'QuickBooks Sync Snapshot',
            },
        ),
    ]
