# Generated by Django 6.0.4 on 2026-04-25 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0005_qbsyncsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('project_address', models.CharField(blank=True, max_length=300)),
                ('project_manager', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_contract_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_timing', models.CharField(choices=[('material_labor', 'Due with Material and Labor'), ('interiors', 'Due with Interiors'), ('immediately', 'Due immediately')], default='immediately', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='stmc_ops.job')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('job', 'number')},
            },
        ),
    ]
