# Generated by Django 6.0.4 on 2026-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0006_jobchangeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExteriorRateCard',
        ),
        migrations.AlterUniqueTogether(
            name='jobcontractoroverride',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobcontractoroverride',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobcustomcharge',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobroofrow',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobslabrow',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='awning_qty',
        ),
        migrations.RemoveField(
            model_name='job',
            name='basement_framing',
        ),
        migrations.RemoveField(
            model_name='job',
            name='chimney_qty',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_boom_pump',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_foam_lf',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_line_pump',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_rebar',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_sqft',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_wire',
        ),
        migrations.RemoveField(
            model_name='job',
            name='conc_zone',
        ),
        migrations.RemoveField(
            model_name='job',
            name='crawl_sf',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cupola_qty',
        ),
        migrations.RemoveField(
            model_name='job',
            name='dbl_doors',
        ),
        migrations.RemoveField(
            model_name='job',
            name='dbl_windows',
        ),
        migrations.RemoveField(
            model_name='job',
            name='deck_shown',
        ),
        migrations.RemoveField(
            model_name='job',
            name='detached_shop',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gauge_26',
        ),
        migrations.RemoveField(
            model_name='job',
            name='punch_amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='s2d_windows',
        ),
        migrations.RemoveField(
            model_name='job',
            name='s2s_windows',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sgl_doors',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sgl_windows',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sheathing',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stone_upgrade',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wainscot_enabled',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wall_rock_sf',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wall_stone_sf',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wall_tuff_sf',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wall_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='windows_above_12',
        ),
        migrations.AddField(
            model_name='job',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='bill_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='bill_state',
            field=models.CharField(default='TN', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='bill_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='bill_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='co_buyer_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='co_buyer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='co_buyer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='concrete_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Concrete portion of the shell budget — flows to Draw 2', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_notes',
            field=models.TextField(blank=True, help_text='Free-text spec notes appended to the contract'),
        ),
        migrations.AddField(
            model_name='job',
            name='contracts_rep',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_rep_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('llc', 'LLC / Business'), ('trust', 'Trust / Estate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='det_shop_conc_labor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Detached shop concrete + labor — flows to Draw 2 shop line', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='det_shop_material',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Detached shop material — flows to Draw 1 shop line', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='labor_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Exterior/framing labor portion of the shell budget — flows to Draw 3', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='manual_living_sf',
            field=models.IntegerField(default=0, help_text='Custom Floor Plan only — user-entered Living SF'),
        ),
        migrations.AddField(
            model_name='job',
            name='order_number_secondary',
            field=models.CharField(blank=True, help_text='Secondary S/M order number for shop/detached garage builds', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='permit_allowance',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='shell_contract',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated total exterior shell contract — entered by sales rep on Step 1', max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='site_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='site_prep_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='site_same_as_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='site_state',
            field=models.CharField(default='TN', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='site_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='site_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='supersedes_prev_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='supersedes_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='foundation_type',
            field=models.CharField(choices=[('slab', 'Monolithic Slab w/ Footers'), ('crawlspace', 'Crawlspace'), ('basement', 'Basement'), ('blockfill', 'Block-and-Fill')], default='slab', help_text='Drives contract template wording (slab vs. crawlspace clauses)', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_mode',
            field=models.CharField(choices=[('shell', 'Shell Only (legacy)'), ('turnkey', 'Turnkey Interior')], default='turnkey', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='p10_material',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Entered on Contract step once material quote returns', max_digits=12),
        ),
        migrations.DeleteModel(
            name='JobConcreteFinishLine',
        ),
        migrations.DeleteModel(
            name='JobContractorOverride',
        ),
        migrations.DeleteModel(
            name='JobCustomCharge',
        ),
        migrations.DeleteModel(
            name='JobRoofRow',
        ),
        migrations.DeleteModel(
            name='JobSlabRow',
        ),
    ]
