# Generated by Django 6.0.4 on 2026-04-27 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0007_delete_exteriorratecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(help_text="JobTradeBudget.trade_name (e.g. 'Cabinets')", max_length=64, unique=True)),
                ('qb_item_id', models.CharField(max_length=32)),
                ('qb_account_id', models.CharField(max_length=32)),
                ('qb_account_name', models.CharField(help_text="QB Chart of Accounts name (e.g. 'Cabinets and Ctops')", max_length=128)),
                ('realm_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='True once a paid Bill has credited this trade. Locks the row.'),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp the puller observed Balance == 0 on the matching Bill.', null=True),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_bill_id',
            field=models.CharField(blank=True, default='', help_text='QB Bill.Id of the payment that locked this row (audit trail).', max_length=32),
        ),
    ]
