# Generated by Django 6.0.4 on 2026-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0008_qbitemmap_jobtradebudget_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbinvoiceevent',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qbinvoiceevent',
            name='qb_due_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
