# Generated by Django 6.0.4 on 2026-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0009_qbinvoiceevent_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdraw',
            name='status',
            field=models.CharField(choices=[('p', 'Paid'), ('i', 'Invoiced (Due)'), ('c', 'Current'), ('x', 'Pending')], default='x', max_length=2),
        ),
    ]
