# Generated by Django 6.0.4 on 2026-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0010_alter_jobdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_bill_doc_number',
            field=models.CharField(blank=True, default='', help_text='Human-readable DocNumber from the matching QB Bill (the real invoice number a person reads in QuickBooks).', max_length=50),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_bill_txn_date',
            field=models.DateField(blank=True, help_text='TxnDate of the matching QB Bill.', null=True),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_bill_vendor',
            field=models.CharField(blank=True, default='', help_text='VendorRef.name from the matching QB Bill.', max_length=120),
        ),
    ]
