# Generated by Django 6.0.4 on 2026-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0011_jobtradebudget_qb_bill_real_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobchangeorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobchangeorder',
            name='qb_invoice_doc_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobchangeorder',
            name='qb_invoice_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobchangeorder',
            name='qb_invoice_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobchangeorder',
            name='qb_invoice_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent to QuickBooks'), ('failed_fallback', 'Local fallback (QB unavailable)')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='jobchangeorder',
            name='qb_invoice_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
