# Generated by Django 6.0.4 on 2026-05-04 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0012_jobchangeorder_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('bt_code', models.CharField(blank=True, default='', max_length=64)),
                ('qb_account_name', models.CharField(blank=True, default='', max_length=128)),
                ('trade_bucket', models.CharField(blank=True, default='', max_length=40)),
                ('draw_number', models.IntegerField(default=0)),
                ('budgeted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qb_bill_refs', models.JSONField(blank=True, default=list)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_budget_lines', to='stmc_ops.job')),
            ],
            options={
                'ordering': ['sort_order', 'po_number'],
                'unique_together': {('job', 'po_number')},
            },
        ),
    ]
