# Generated by Django 6.0.4 on 2026-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0013_jobbudgetlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qb_bank_account_id',
            field=models.CharField(blank=True, default='', help_text='QB Account.Id of the Bank/Credit Card account this branch pays bills from.', max_length=32),
        ),
        migrations.AddField(
            model_name='branch',
            name='qb_bank_account_name',
            field=models.CharField(blank=True, default='', help_text='QB Account.Name (cached for display) of the mapped bank account.', max_length=128),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_paid_from_account_id',
            field=models.CharField(blank=True, default='', help_text='QB Account.Id of the Bank/Credit Card account the matching BillPayment drew from.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobtradebudget',
            name='qb_paid_from_account_name',
            field=models.CharField(blank=True, default='', help_text="QB Account.Name of the BillPayment's BankAccountRef (cached for display).", max_length=128),
        ),
    ]
