# Generated by Django 6.0.4 on 2026-05-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stmc_ops', '0014_branch_qb_bank_account_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QbItemMap',
        ),
    ]
