from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("login/panel/", views.login_panel_view, name="login_panel"),
    path("login/submit/", views.login_submit_view, name="login_submit"),
    path("logout/", views.logout_view, name="logout"),
    path("sales/", views.sales_view, name="sales"),
    path("sales/shell/", views.sales_shell_view, name="sales_shell"),
    path("sales/shell/<int:job_id>/", views.sales_shell_view, name="sales_shell_edit"),
    path("sales/turnkey/", views.sales_turnkey_view, name="sales_turnkey"),
    path("sales/turnkey/<int:job_id>/", views.sales_turnkey_view, name="sales_turnkey_edit"),
    path("sales/overview/", views.sales_overview_view, name="sales_overview"),
    path("sales/overview/in-progress-panel/", views.sales_in_progress_panel_view, name="sales_in_progress_panel"),
    path("sales/overview/closed-panel/", views.sales_closed_panel_view, name="sales_closed_panel"),
    path("sales/overview/rates-panel/", views.sales_rates_panel_view, name="sales_rates_panel"),
    path("sales/overview/header-panel/", views.sales_header_panel_view, name="sales_header_panel"),
    path("sales/overview/leads-panel/", views.sales_leads_panel_view, name="sales_leads_panel"),
    path("sales/leads/new/", views.sales_new_lead_view, name="sales_new_lead"),
    path("sales/leads/<int:job_id>/edit/", views.sales_edit_lead_view, name="sales_edit_lead"),
    path("sales/leads/<int:job_id>/delete/", views.sales_delete_lead_view, name="sales_delete_lead"),
    path("sales/leads/<int:job_id>/convert/", views.sales_convert_lead_view, name="sales_convert_lead"),
    path("sales/floor-plan-pdfs/<str:filename>/", views.sales_floor_plan_pdf_view, name="sales_floor_plan_pdf"),
    path("sales/contracts/seed-data/", views.sales_contract_seed_data_view, name="sales_contract_seed_data"),
    path("sales/app/finalize-contract/<int:job_id>/", views.sales_finalize_contract_view, name="sales_finalize_contract"),
    path("app/seed-data/", views.app_seed_data_view, name="app_seed_data"),
    path("app/draw/complete/", views.mark_draw_complete_view, name="mark_draw_complete"),
    path("app/save-contract/", views.save_contract_view, name="save_contract"),
    path("manager/", views.manager_view, name="manager"),
    path("manager/builds-panel/", views.manager_builds_panel_view, name="manager_builds_panel"),
    path("manager/budgets-panel/", views.manager_budgets_panel_view, name="manager_budgets_panel"),
    path("manager/draws-panel/", views.manager_draws_panel_view, name="manager_draws_panel"),
    path("manager/panel/complete/", views.manager_panel_mark_complete_view, name="manager_panel_complete"),
    path("owner/", views.owner_view, name="owner"),
    path("owner/dashboard-panel/", views.owner_dashboard_panel_view, name="owner_dashboard_panel"),
    path("owner/all-projects-panel/", views.owner_all_projects_panel_view, name="owner_all_projects_panel"),
    path("owner/payments-panel/", views.owner_payments_panel_view, name="owner_payments_panel"),
    # ── QuickBooks Online (Intuit) OAuth ──
    path("qb/connect/", views.qb_connect_view, name="qb_connect"),
    path("qb/callback/", views.qb_callback_view, name="qb_callback"),
    path("qb/disconnect/", views.qb_disconnect_view, name="qb_disconnect"),
    path("owner/qb-status/", views.qb_status_view, name="qb_status"),
    # ── Owner bell notifications ──
    path("owner/notifications/bell/", views.owner_notifications_bell_view,
         name="owner_notifications_bell"),
    path("owner/notifications/dropdown/", views.owner_notifications_dropdown_view,
         name="owner_notifications_dropdown"),
    path("owner/notifications/<int:event_id>/read/",
         views.owner_notification_mark_read_view,
         name="owner_notification_mark_read"),
    path("owner/notifications/mark-all-read/",
         views.owner_notifications_mark_all_read_view,
         name="owner_notifications_mark_all_read"),
]
